plugins {
	id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencies {
	implementation project(':temon-common')
	annotationProcessor 'org.projectlombok:lombok:1.18.38'

	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.kafka:spring-kafka'

	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.16'

	implementation 'me.paulschwarz:spring-dotenv:4.0.0'

	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	testImplementation 'org.springframework.security:spring-security-test'
}

springBoot {
    mainClass = 'com.example.temon.commerceservice.TemonCommerceServiceApplication'
}